// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' ;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGuTdbgDv7zjMsqCX46qvgOiOUtOk4t48',
    appId: '1:515172108240:web:0c1bc967e32236400c5bd5',
    messagingSenderId: '515172108240',
    projectId: 'ecommarce-ea878',
    authDomain: 'ecommarce-ea878.firebaseapp.com',
    storageBucket: 'ecommarce-ea878.appspot.com',
    measurementId: 'G-CYZ89XGX5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOI7TWrP5fZyOUGNF1X0NEPQh3LmDv1bo',
    appId: '1:515172108240:android:f06e55bb7e3a63da0c5bd5',
    messagingSenderId: '515172108240',
    projectId: 'ecommarce-ea878',
    storageBucket: 'ecommarce-ea878.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTaXo403ia7GmKNc87hUIOhSyYO-Wz_Tg',
    appId: '1:515172108240:ios:731f41317cfd78c60c5bd5',
    messagingSenderId: '515172108240',
    projectId: 'ecommarce-ea878',
    storageBucket: 'ecommarce-ea878.appspot.com',
    iosBundleId: 'com.example.online',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTaXo403ia7GmKNc87hUIOhSyYO-Wz_Tg',
    appId: '1:515172108240:ios:eeb06da95c7b45ea0c5bd5',
    messagingSenderId: '515172108240',
    projectId: 'ecommarce-ea878',
    storageBucket: 'ecommarce-ea878.appspot.com',
    iosBundleId: 'com.example.online.RunnerTests',
  );
}
